#CLASE 14 DE OCTUBRE

In [ ]:
pantalones = 55
paquetes = 7
total = int(pantalones/paquetes)
print("En cada paquete hay un total de ", total)

En cada paquete hay un total de  7


In [ ]:
cantotal=pantalones - total*paquetes # tambien ppodria habver sido pantalones%paquetes
print(f"Me sobran: {cantotal} pantalones")
p = 70 #precio individual
print(f"El monto de los individuales es: {cantotal*p} ")

Me sobran:  6 pantalones
El monto de los individuales es: 420 


##listas

In [ ]:
# listas tienen [ ]
# Son datos agrupados de cualquier tipo
lista_1=[1,2]
print(lista_1)


[1, 2]


In [ ]:
lista_1[0]
lista_1.append('Jesus')

In [ ]:
lista_1[2]

'Jesus'

In [ ]:
lista_2=[1,2]
lista_3=['jesus','ortiz']

In [ ]:
lista_4=lista_2+lista_3
lista_4

[1, 2, 'jesus', 'ortiz']

In [ ]:
lista_2.extend(lista_3)


In [ ]:
lista_2

[1, 2, 'jesus', 'ortiz']

In [ ]:
lista_5=[*lista_2,*lista_3]
lista_5

[1, 2, 'jesus', 'ortiz', 'jesus', 'ortiz']

In [ ]:
lista_2.insert(3,"Hola") #lo inserto sin eliminar ningun valor

In [ ]:
lista_2
lista_5[3]=5 #me reemplaza el valor

In [ ]:
lista_5

[1, 2, 'jesus', 5, 'jesus', 'ortiz']

In [ ]:
prueba = 'Hola'
prueba[0]


'H'

In [ ]:
prueba[-1]

'a'

###Listas


In [ ]:
numeros_primos=[1,2,3,5,7,11,13,17,19,23,29,31]
l=len(numeros_primos)

print(f'El tercer valor es: {numeros_primos[2]}')
print(f'El septimo valor es: {numeros_primos[6]}')
print(f'El ultimo valor es: {numeros_primos[l-1]}')


El tercer valor es: 3
El septimo valor es: 13
El ultimo valor es: 31


In [ ]:
alumnos = ['Armando', 'Bruno', 'Claudia', 'Daniela', 'Alejandra']


In [ ]:
print('Alejandra' not in alumnos)

print('Alejandra' in alumnos)

False
True


## TUPLAS : no se pueden modificar (las listas si se pueden modificar)


In [ ]:
tupla_1=(1,2)

In [ ]:
tupla_1.append(5)
tupla_1[1]=3

AttributeError: ignored

In [ ]:
lista_1.append(tupla_1)

In [ ]:
lista_1.append(lista_5)
lista_1

[1, 2, 'Jesus', (1, 2), [1, 2, 'jesus', 5, 'jesus', 'ortiz']]

In [ ]:
lista_1[-1][3]

5

## DICCIONARIOS {}: Elemento de datos no ordenados, no tiene posiciones si no que sus valores se guardan con una clave

In [ ]:
my_dicc = {'1a':1}

In [ ]:
my_dicc[0] # en el diccionario esto no funciona
my_dicc.append(1) #tampoco funciona

KeyError: ignored

In [ ]:
my_dicc['1a']

1

In [ ]:
my_dicc['jesus']='ortiz'

In [ ]:
my_dicc['hola']=[1,2]
my_dicc

{'1a': 1, 'jesus': 'ortiz', 'hola': [1, 2]}

In [ ]:
my_dicc['hola'].append(3) #esto funciona por que se trata de una lista

In [ ]:
my_dicc

{'1a': 1, 'jesus': 'ortiz', 'hola': [1, 2, 3]}

In [ ]:
a=3
b=3


In [ ]:
if (a==b):
  print("hola")
  print("todos")
  a=2
  print(a+b)
else:
  a=b
  print('estoy haciendo trampa')


estoy haciendo trampa


In [ ]:
if (a>5):
  print("en mayor que 5")
elif (a<0):
  print("es negativo")
elif (a==0):
  print("a es cero")
else:
  print("a es mayor que cero y menor que 5")


a es mayor que cero y menor que 5


In [ ]:
estudiantes = ["jesus", "jose", "luisa", "antonia", "maria"]

In [ ]:
for estudiante in estudiantes:
  print("hola",estudiante)

hola  jesus
hola  jose
hola  luisa
hola  antonia
hola  maria


In [ ]:
for i in range(0,100,5):
  print(i)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95


In [ ]:
for i in range(len(estudiantes)):
   print("hola",estudiantes[i])

hola jesus
hola jose
hola luisa
hola antonia
hola maria


In [ ]:
amigos= ['natalia','francisca','daniel','patricio','matias']
numero= [ 82654799, 75426533, 85471955, 52346981, 75498625]

for i in range(len(amigos)):
  print(f'Buenos días {amigos[i]}, ¿tu numero todavía es {numero[i]}?')


Buenos días natalia, ¿tu numero todavía es 82654799?
Buenos días francisca, ¿tu numero todavía es 75426533?
Buenos días daniel, ¿tu numero todavía es 85471955?
Buenos días patricio, ¿tu numero todavía es 52346981?
Buenos días matias, ¿tu numero todavía es 75498625?


In [ ]:
import pandas
pandas.DataFrame()

In [ ]:
import numpy as np


In [ ]:
vector_1 = np.array([2,4,6,8,10])
vector_1

array([ 2,  4,  6,  8, 10])

In [ ]:
 vector_2=np.array([])
 vector_2

In [ ]:
reto = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
reto
pandas.DataFrame(reto)

0   1   2   3   4   5
0   1   2   3   4   5   6
1   7   8   9  10  11  12
2  13  14  15  16  17  18

In [ ]:
a= int(input ("por favor seleccione 1 para pizza vegetariana o 2 para pizza no vegetariana o 3 si quieres salir: "))
ing1=['Pimiento','Tofu']
ing2=['Peperoni','Jamón','Salmón']


while (a!=3):
  if a==1:
    print(f'los ingredientes disponibles son: \n 1: Pimiento  \n 2:Tofu')
    g = int(input('¿Cúal es su elección?: '))
    if g==1 or g==2:
      print(f'Su orden es: una pizza vegetariana, con mozzarella, tomate y {ing1[g-1]}')
      a= int(input ("por favor seleccione 1 para pizza vegetariana o 2 para pizza no vegetariana o 3 si quieres salir: "))

    else:
      print('Error en la orden, comience nuevamente')
      a= int(input ("por favor seleccione 1 para pizza vegetariana o 2 para pizza no vegetariana o 3 si quieres salir: "))

  elif a==2:
    print(f'los ingredientes disponibles son:  \n 1: Peperoni  \n 2: Jamón  \n 3: Salmón')
    h = int(input('¿Cúal es su elección?: '))
    if h==1 or h==2 or h==3:
      print(f'Su orden es: una pizza no vegetariana, con mozzarella, tomate y {ing2[h-1]}')
      a= int(input ("por favor seleccione 1 para pizza vegetariana o 2 para pizza no vegetariana o 3 si quieres salir: "))

    else:
      print('Error en la orden, comience nuevamente')
      a= int(input ("por favor seleccione 1 para pizza vegetariana o 2 para pizza no vegetariana o 3 si quieres salir: "))

  else:
    print('Error en la orden, comience nuevamente')
    a= int(input ("por favor seleccione 1 para pizza vegetariana o 2 para pizza no vegetariana o 3 si quieres salir: "))



por favor seleccione 1 para pizza vegetariana o 2 para pizza no vegetariana o 3 si quieres salir: 3


In [ ]:
ejemplo_1=np.zeros(4)

ejemplo_2=np.zeros((2,5))

ejemplo_3=np.ones(3)

ejemplo_4=np.ones((2,5))

ejemplo_5=np.full((2,3),12)
print(ejemplo_1)
print(ejemplo_2)
print(ejemplo_3)
print(ejemplo_4)
print(ejemplo_5)


[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[12 12 12]
 [12 12 12]]


In [ ]:
df=pd.DataFrame({'Mes': ['ene','feb','mar','may','jun'], 'Ventas': [10,15,6,11,20]})
df